FROM maven:3.6

COPY ./repository /root/.m2/repository
COPY ./ReachCheck /app/ReachCheck
COPY ./postgis-jts /app/postgis-jts

# Install ReachCheck
WORKDIR /app/ReachCheck
RUN mvn install -Dmaven.test.skip=true

# Pre-execute once, download the necessary package
WORKDIR /app/postgis-jts
RUN mvn -f=./pom.xml -DtargetJar=./target/postgis-jts-2.2.1.jar -Dmaven.test.skip=true org.example:ReachCheck:1.0:detectVul -e

CMD ["mvn", "-f=./pom.xml", "-DtargetJar=./target/postgis-jts-2.2.1.jar", "-Dmaven.test.skip=true", "org.example:ReachCheck:1.0:detectVul", "-e"]